services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - ptsr_fastapi:/var/lib/postgresql/data/ # том для сохранения данных
    networks:
      - my_network_ptsrapp
    ports:
      - "5433:5432"

volumes:
  ptsr_fastapi:
    name: "ptsr_fastapi"

networks:
  my_network_ptsrapp:
    driver: bridge