services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - back-healify/.env
    volumes:
      - ptsr_fastapi:/var/lib/postgresql/data/ # том для сохранения данных
    networks:
      - my_network_ptsrapp
#    ports:
#      - "5434:5432"

  web:
    build: back-healify
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - back-healify/.env
    networks:
      - my_network_ptsrapp

volumes:
  ptsr_fastapi:
    name: "ptsr_fastapi"

networks:
  my_network_ptsrapp:
    driver: bridge