services:
  db:
    container_name: healify-db
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - healify_db:/var/lib/postgresql/data/
    networks:
      - healify_network
    restart: unless-stopped

  backend:
    container_name: healify-backend
    image: healify-web-app:latest
    pull_policy: never
    build:
      context: ./back-healify
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - healify_network
    restart: unless-stopped

  frontend:
    container_name: healify-frontend
    image: healify-front:latest
    pull_policy: never
    build:
      context: ./front-healify
    networks:
      - healify_network
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - healify_network
    restart: unless-stopped

volumes:
  healify_db:
    name: "healify_db"

networks:
  healify_network:
    driver: bridge
